analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3096131,\\n  \\"name\\"\: \\"demo-MB\\",\\n  \\"teamId\\"\: 3067994,\\n  \\"organizationId\\"\: 2497043,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3067994\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=false
analytics.testcloud.hub.switchHub.enable=false
